spring:
  datasource:
    url: jdbc:postgresql://31.220.84.140:5432/storage
    username: mockwise
    password: mockwise_pg_password2026

  jpa:
    show-sql: true

minio:
  endpoint: http://31.220.84.140:9000
  public-endpoint: http://31.220.84.140:9000
  access-key: minioadmin
  secret-key: ${MINIO_ROOT_PASSWORD}

internal:
  auth:
    api-key: dev-internal-key-change-me

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
