spring:
  application:
    name: mail-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: mail-service-group-v4
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.mail_service.dto.EmailEvent

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from-name: ${MAIL_FROM_NAME:MockWise}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8087

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka.clients.consumer: INFO
    org.apache.kafka.clients.NetworkClient: WARN

