spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: IAMHikariPool
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 6000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}


server:
  port: 8081
  servlet:
    context-path: /api/v1/iam

external:
  services:
    profile-service:
      url: ${EXTERNAL_SERVICES_PROFILE_SERVICE_URL:http://localhost:8082/api/v1/profiles}

app:
  jwt:
    issuer: mockwise-iam
    audience: mockwise-api
    access-ttl-seconds: 600
    refresh-ttl-seconds: 1209600
    active-kid: rsa-key-2025-10
    JWT_HMAC_SECRET: ${JWT_HMAC_SECRET}
    max-refresh-sessions: 5
    cookie-secure: ${JWT_COOKIE_SECURE:false}

  otp:
    key_otp_verify_account: "key_verify_"
    key_otp_forgot_pass: "key_forgot_password_"
    time_expire: 300
api:
  response:
    enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
