package com.mockwise.interview.planner;

import com.mockwise.interview.assessment.WeakTarget;
import com.mockwise.interview.entity.BlueprintTopic;
import com.mockwise.interview.entity.enums.Difficulty;

/**
 * What the planner decided to do next, expressed as a discriminated union
 * so the caller is forced to handle every case in a switch and the compiler
 * catches a missed branch.
 *
 * <p>Three outcomes — and only three — make sense after the planner sees
 * an answer come back: ask a follow-up about the same topic, move on to
 * a new topic, or stop the session entirely. Anything more granular
 * (e.g. "ask follow-up at lower difficulty" vs "ask follow-up at same
 * difficulty") lives inside the {@link AskFollowUp} variant rather than
 * polluting this top-level enumeration.
 *
 * <p>The planner is a pure function — it does not mutate the session/topic
 * rows itself. The caller applies whatever side-effects the chosen decision
 * implies, after persisting the verdict, in the same database transaction.
 * Keeps the planner unit-testable with no JPA fixture.
 */
public sealed interface PlannerDecision
        permits PlannerDecision.AskFollowUp,
                PlannerDecision.MoveToNextTopic,
                PlannerDecision.EndSession {

    /**
     * Stay on the current topic and ask a follow-up. The caller decides
     * pre-authored vs AI-generated by trying question-bank first
     * (Tier 1 in §5.3 of the selection doc).
     *
     * @param weakTarget        the target to probe — drives both the
     *                          question-bank lookup and the AI prompt
     * @param difficulty        difficulty for the follow-up; never harder
     *                          than the parent question
     */
    record AskFollowUp(
            WeakTarget weakTarget,
            Difficulty difficulty
    ) implements PlannerDecision {}

    /**
     * Close the current topic and start a new one. Carries the next topic
     * pulled from the blueprint plus the opening difficulty after applying
     * stretch / global offset adjustments.
     */
    record MoveToNextTopic(
            BlueprintTopic nextTopic,
            Difficulty openingDifficulty
    ) implements PlannerDecision {}

    /**
     * Stop accepting new questions. The reason field is for telemetry and
     * the user-facing report; the planner never picks more than one
     * EndSession reason at a time so the highest-priority condition wins
     * (coverage > budget > time > critical-mismatch > user-stop).
     */
    record EndSession(EndReason reason) implements PlannerDecision {

        public enum EndReason {
            /** Every topic in the blueprint has been at least probed. */
            COVERAGE_COMPLETE,
            /** Total question count (including follow-ups) hit the budget. */
            QUESTION_BUDGET_EXHAUSTED,
            /** Wall-clock time on the session exceeded the blueprint cap. */
            TIME_BUDGET_EXHAUSTED,
            /** consecutive_unknown_count escalated past the safety net. */
            CRITICAL_LEVEL_MISMATCH
        }
    }
}
